# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 20.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng test ngx-onboarding --watch=false --browsers=ChromeHeadless --code-coverage
    npm run package
  displayName: 'test, build & package'

- task: PublishTestResults@2
  inputs:
      testRunner: JUnit
      testResultsFiles: ./reports/junit.xml
  displayName: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/reports/coverage/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/reports/coverage'
  displayName: 'Publish test coverage'
